[package]
name = "arbitrum-demo"
version = "0.1.0"
edition = "2021"

[dependencies]

anyhow = "1.0"
url = "2.3.1"
tokio = { version = "1.27.0", features = ["full"] }
futures = "0.3.30"
native-tls = "0.2.11"
tokio-tungstenite = { version = "0.20.1", features = ["native-tls"] }
